# Generated by Django 4.2.7 on 2023-11-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_language_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(default=1, help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
