# Generated by Django 4.2.7 on 2023-11-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_book_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
